#%RAML 1.0 DataType
properties:
  status:
    type: string
    description: Either one of - S=Success, F=Fail
    required: true
  message:
    type: string
    description: Short message sent back to the calling application
    required: true
    