http:
  port: "8081"
  request:
    response-timeout: "30000"
    reconnection-frequency: "3000"
    reconnection-count: "3"  
api:
  id: "17342363"
  
donations-papi:  
  host: "donations-papi.us-e2.cloudhub.io"
  port: "80"
  create-donation-item-path: "/api/donors/{donorID}/donationItems"
  update-token-path: "/api/device-token"
  
donations-sapi:  
  host: "donations-sapi.us-e2.cloudhub.io"
  port: "80"
  create-donation-item-path: "/api/donors/{donorID}/donationItems"
  get-donor-donations-path: "/api/donors/{donorID}/donationItems"
  get-beneficiary-donation-items-path: "/api/beneficiary/{beneficiaryID}/donationItems"
  update-donation-item-path: "/api/donationItems/{donationItemID}"
  
donor-sapi:
  host: "donors-sapi.us-e2.cloudhub.io"
  port: "80"
  get-donor-details-path: "/api/donors/{donorID}"
  post-donor-details-path: "/api/donors"  
  
beneficiary-sapi:
  host: "beneficiary-sapi.us-e2.cloudhub.io"
  port: "80"
  get-nearby-beneficiaries-path: "/api/beneficiary"
  post-beneficiaries-path: "/api/beneficiary"
  get-beneficiary-details-path: "/api/beneficiary/{beneficiaryID}"
  search-radius: "4000"  
  
attachments-sapi:  
  host: "attachments-sapi.us-e2.cloudhub.io"
  port: "80"
  create-attachment-path: "api/v1/attachment"
  
  