#%RAML 1.0 DataType
properties:
  meta : !include exchange_modules/4f5614e6-449c-4800-8081-0011457a38ca/common-response-types/1.0.0/dataTypes/meta-dataType.raml
  data : !include donor-request-type.raml
