http:
  port: "![HicG+oZWkiI=]"
api:
  id: "![Qhd9IPUMFSQ=]"

aws:
  access-key: "![5yJUmplda6IWAIpHIfwDHf7ppUQQeDJk]"
  secret-key: "![SuKjrSdlXfT35jREFRMojVnEVBvHAuk5aOaWVTp8CvRAtIVzRJ5wuHS3ViihC3uB]"
  region: "![Qhd9IPUMFSQ=]"


