#%RAML 1.0 NamedExample
value:
  apiName: donor-api
  version: 1
  correlationId: e2csdf8b60-sdf-11esdf9-8843b4-64533446d1
  timestamp: 2021-05-11T22:18:45.964-06:00
  "meta": {
    "status": "F",
     "message": ["404-Resource Not Found"]
  }
  "data": null
